export default {
  SELECTED_VEHICLE: 'SELECTED_VEHICLE',

  GET_VEHICLES_REQUEST: 'GET_VEHICLES_REQUEST',
  GET_VEHICLES_SUCCESS: 'GET_VEHICLES_SUCCESS',
  GET_VEHICLES_FAILURE: 'GET_VEHICLES_FAILURE',

  GET_LOG_OF_VEHICLE_REQUEST: 'GET_LOG_OF_VEHICLE_REQUEST',
  GET_LOG_OF_VEHICLE_SUCCESS: 'GET_LOG_OF_VEHICLE_SUCCESS',
  GET_LOG_OF_VEHICLE_FAILURE: 'GET_LOG_OF_VEHICLE_FAILURE',

  CREATE_VEHICLE_REQUEST: 'CREATE_VEHICLE_REQUEST',
  CREATE_VEHICLE_SUCCESS: 'CREATE_VEHICLE_SUCCESS',
  CREATE_VEHICLE_FAILURE: 'CREATE_VEHICLE_FAILURE',

  UPDATE_VEHICLE_REQUEST: 'UPDATE_VEHICLE_REQUEST',
  UPDATE_VEHICLE_SUCCESS: 'UPDATE_VEHICLE_SUCCESS',
  UPDATE_VEHICLE_FAILURE: 'UPDATE_VEHICLE_FAILURE',

  DELETE_VEHICLE_REQUEST: 'DELETE_VEHICLE_REQUEST',
  DELETE_VEHICLE_SUCCESS: 'DELETE_VEHICLE_SUCCESS',
  DELETE_VEHICLE_FAILURE: 'DELETE_VEHICLE_FAILURE',
};
