export default {
  SELECTED_CUSTOMER: 'SELECTED_CUSTOMER',

  GET_CUSTOMERS_REQUEST: 'GET_CUSTOMERS_REQUEST',
  GET_CUSTOMERS_SUCCESS: 'GET_CUSTOMERS_SUCCESS',
  GET_CUSTOMERS_FAILURE: 'GET_CUSTOMERS_FAILURE',

  GET_CUSTOMER_REQUEST: 'GET_CUSTOMER_REQUEST',
  GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
  GET_CUSTOMER_FAILURE: 'GET_CUSTOMER_FAILURE',

  GET_VEHICLE_OF_CUSTOMER_REQUEST: 'GET_VEHICLE_OF_CUSTOMER_REQUEST',
  GET_VEHICLE_OF_CUSTOMER_SUCCESS: 'GET_VEHICLE_OF_CUSTOMER_SUCCESS',
  GET_VEHICLE_OF_CUSTOMER_FAILURE: 'GET_VEHICLE_OF_CUSTOMER_FAILURE',

  GET_TRANSACTION_OF_CUSTOMER_REQUEST: 'GET_TRANSACTION_OF_CUSTOMER_REQUEST',
  GET_TRANSACTION_OF_CUSTOMER_SUCCESS: 'GET_TRANSACTION_OF_CUSTOMER_SUCCESS',
  GET_TRANSACTION_OF_CUSTOMER_FAILURE: 'GET_TRANSACTION_OF_CUSTOMER_FAILURE',

  CREATE_CUSTOMER_REQUEST: 'CREATE_CUSTOMER_REQUEST',
  CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
  CREATE_CUSTOMER_FAILURE: 'CREATE_CUSTOMER_FAILURE',

  UPDATE_CUSTOMER_REQUEST: 'UPDATE_CUSTOMER_REQUEST',
  UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
  UPDATE_CUSTOMER_FAILURE: 'UPDATE_CUSTOMER_FAILURE',

  DELETE_CUSTOMER_REQUEST: 'DELETE_CUSTOMER_REQUEST',
  DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
  DELETE_CUSTOMER_FAILURE: 'DELETE_CUSTOMER_FAILURE',

  ADD_VEHICLE_TO_CUSTOMER_REQUEST: 'ADD_VEHICLE_TO_CUSTOMER_REQUEST',
  ADD_VEHICLE_TO_CUSTOMER_SUCCESS: 'ADD_VEHICLE_TO_CUSTOMER_SUCCESS',
  ADD_VEHICLE_TO_CUSTOMER_FAILURE: 'ADD_VEHICLE_TO_CUSTOMER_FAILURE',

  REMOVE_VEHICLE_OF_CUSTOMER_REQUEST: 'REMOVE_VEHICLE_OF_CUSTOMER_REQUEST',
  REMOVE_VEHICLE_OF_CUSTOMER_SUCCESS: 'REMOVE_VEHICLE_OF_CUSTOMER_SUCCESS',
  REMOVE_VEHICLE_OF_CUSTOMER_FAILURE: 'REMOVE_VEHICLE_OF_CUSTOMER_FAILURE',
};
