export default {
  GET_VEHICLE_LOG_STATISTICS_REQUEST: 'GET_VEHICLE_LOG_STATISTICS_REQUEST',
  GET_VEHICLE_LOG_STATISTICS_SUCCESS: 'GET_VEHICLE_LOG_STATISTICS_SUCCESS',
  GET_VEHICLE_LOG_STATISTICS_FAILURE: 'GET_VEHICLE_LOG_STATISTICS_FAILURE',
};
