export default {
  // #region --- Site ---
  SELECTED_SITE: 'SELECTED_SITE',

  GET_SITES_REQUEST: 'GET_SITES_REQUEST',
  GET_SITES_SUCCESS: 'GET_SITES_SUCCESS',
  GET_SITES_FAILURE: 'GET_SITES_FAILURE',

  GET_SITE_REQUEST: 'GET_SITE_REQUEST',
  GET_SITE_SUCCESS: 'GET_SITE_SUCCESS',
  GET_SITE_FAILURE: 'GET_SITE_FAILURE',

  GET_CAMERA_OF_SITE_REQUEST: 'GET_CAMERA_OF_SITE_REQUEST',
  GET_CAMERA_OF_SITE_SUCCESS: 'GET_CAMERA_OF_SITE_SUCCESS',
  GET_CAMERA_OF_SITE_FAILURE: 'GET_CAMERA_OF_SITE_FAILURE',

  CREATE_SITE_REQUEST: 'CREATE_SITE_REQUEST',
  CREATE_SITE_SUCCESS: 'CREATE_SITE_SUCCESS',
  CREATE_SITE_FAILURE: 'CREATE_SITE_FAILURE',

  UPDATE_SITE_REQUEST: 'UPDATE_SITE_REQUEST',
  UPDATE_SITE_SUCCESS: 'UPDATE_SITE_SUCCESS',
  UPDATE_SITE_FAILURE: 'UPDATE_SITE_FAILURE',

  DELETE_SITE_REQUEST: 'DELETE_SITE_REQUEST',
  DELETE_SITE_SUCCESS: 'DELETE_SITE_SUCCESS',
  DELETE_SITE_FAILURE: 'DELETE_SITE_FAILURE',

  ADD_CAMERA_TO_SITE_REQUEST: 'ADD_CAMERA_TO_SITE_REQUEST',
  ADD_CAMERA_TO_SITE_SUCCESS: 'ADD_CAMERA_TO_SITE_SUCCESS',
  ADD_CAMERA_TO_SITE_FAILURE: 'ADD_CAMERA_TO_SITE_FAILURE',

  REMOVE_CAMERA_OF_SITE_REQUEST: 'REMOVE_CAMERA_OF_SITE_REQUEST',
  REMOVE_CAMERA_OF_SITE_SUCCESS: 'REMOVE_CAMERA_OF_SITE_SUCCESS',
  REMOVE_CAMERA_OF_SITE_FAILURE: 'REMOVE_CAMERA_OF_SITE_FAILURE',
  // #endregion

  // #region --- Camera ---
  GET_CAMERAS_REQUEST: 'GET_CAMERAS_REQUEST',
  GET_CAMERAS_SUCCESS: 'GET_CAMERAS_SUCCESS',
  GET_CAMERAS_FAILURE: 'GET_CAMERAS_FAILURE',

  GET_CAMERA_REQUEST: 'GET_CAMERA_REQUEST',
  GET_CAMERA_SUCCESS: 'GET_CAMERA_SUCCESS',
  GET_CAMERA_FAILURE: 'GET_CAMERA_FAILURE',

  CREATE_CAMERA_REQUEST: 'CREATE_CAMERA_REQUEST',
  CREATE_CAMERA_SUCCESS: 'CREATE_CAMERA_SUCCESS',
  CREATE_CAMERA_FAILURE: 'CREATE_CAMERA_FAILURE',

  UPDATE_CAMERA_REQUEST: 'UPDATE_CAMERA_REQUEST',
  UPDATE_CAMERA_SUCCESS: 'UPDATE_CAMERA_SUCCESS',
  UPDATE_CAMERA_FAILURE: 'UPDATE_CAMERA_FAILURE',

  DELETE_CAMERA_REQUEST: 'DELETE_CAMERA_REQUEST',
  DELETE_CAMERA_SUCCESS: 'DELETE_CAMERA_SUCCESS',
  DELETE_CAMERA_FAILURE: 'DELETE_CAMERA_FAILURE',
  // #endregion
};
