export default {
  LOG_IN_REQUEST: 'LOG_IN_REQUEST',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',

  LOG_OUT: 'LOG_OUT',

  SET_TOKEN: 'SET_TOKEN',

  GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',

  GET_PERMISSION_OF_USER_INFO_REQUEST: 'GET_PERMISSION_OF_USER_INFO_REQUEST',
  GET_PERMISSION_OF_USER_INFO_SUCCESS: 'GET_PERMISSION_OF_USER_INFO_SUCCESS',
  GET_PERMISSION_OF_USER_INFO_FAILURE: 'GET_PERMISSION_OF_USER_INFO_FAILURE',

  SHOW_CONFIRM_MODAL: 'SHOW_CONFIRM_MODAL',
  SHOW_FORWARD_MODAL: 'SHOW_FORWARD_MODAL',
  SHOW_INFO_MODAL: 'SHOW_INFO_MODAL',
  SHOW_ERROR_MODAL: 'SHOW_ERROR_MODAL',
  SHOW_UPLOAD_MODAL: 'SHOW_UPLOAD_MODAL',
  SHOW_DOWNLOAD_MODAL: 'SHOW_DOWNLOAD_MODAL',

  UPLOAD_REQUEST: 'UPLOAD_REQUEST',
  UPLOAD_SUCCESS: 'UPLOAD_SUCCESS',
  UPLOAD_FAILURE: 'UPLOAD_FAILURE',

  DOWNLOAD_REQUEST: 'DOWNLOAD_REQUEST',
  DOWNLOAD_SUCCESS: 'DOWNLOAD_SUCCESS',
  DOWNLOAD_FAILURE: 'DOWNLOAD_FAILURE',
};
